#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Register The Composer Auto Loader
|--------------------------------------------------------------------------
*/

require __DIR__.'/vendor/autoload.php';

use Busayo\ProcessArg;

/*
|--------------------------------------------------------------------------
| Call the ProcessArg Class to take in the commands and process faces
|--------------------------------------------------------------------------
*/
$app = new ProcessArg($argv);

$app->spitOutFaces();
